id: IB6394890
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:18:00.596527
last_modified: 2023-02-10 00:18:00.596621
source_metadata:
  title: 'MSV 6,09: Māṇavikā'
  language: zh
bases:
  D4CD:
    base_file: D4CD.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
